name = "Horrorpack"
author = "Shadow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5aff0ad3a03ba339e1a6c4879d1d853e266b2d61e739d97e418bf0a255c51db7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.65"
