name = "Horrorpack: Re-Revamped"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95d3e8896151566803ebe1da9b0ca0427158ae4c5bbd02094e418d7019cf735f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
