name = "Horrorpack"
author = "Shadow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f8288ea171693f7d0b3ee1202e9f1b9e8205e1f843c29de27f6d4ca8e5065a9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.65"
