name = "Horrorpack"
author = "Shadow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2add92d4faa026d818ceb2792783df3731616b09c9d43f7e33097f6024802a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.61"
