name = "Horrorpack"
author = "shadow"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d4505ceaf82cc4e1d0ac445554fd6534d873b26ff439382065b446d0c87d383"

[versions]
forge = "47.2.1"
minecraft = "1.20.1"
