name = "AbyssalCraft Integration"
filename = "AbyssalCraft Integration-1.12.2-1.11.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2959/100/AbyssalCraft Integration-1.12.2-1.11.2.jar"
hash-format = "murmur2"
hash = "280960959"

[update]
[update.curseforge]
file-id = 2959100
project-id = 234851
release-channel = "beta"
