name = "Atum 2: Return to the Sands"
filename = "Atum-1.12.2-2.0.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3116/599/Atum-1.12.2-2.0.20.jar"
hash-format = "murmur2"
hash = "3222925620"

[update]
[update.curseforge]
file-id = 3116599
project-id = 59621
release-channel = "beta"
