name = "Baubley Heart Canisters"
filename = "baubley-heart-canisters-1.12.2-2.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2721/67/baubley-heart-canisters-1.12.2-2.0.3.jar"
hash-format = "murmur2"
hash = "957876240"

[update]
[update.curseforge]
file-id = 2721067
project-id = 282947
release-channel = "beta"
