name = "Bloodmoon"
filename = "Bloodmoon-MC1.12.2-1.5.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2537/917/Bloodmoon-MC1.12.2-1.5.3.jar"
hash-format = "murmur2"
hash = "2259388848"

[update]
[update.curseforge]
file-id = 2537917
project-id = 226321
release-channel = "beta"
