name = "Bookshelf"
filename = "Bookshelf-1.12.2-2.3.590.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2836/960/Bookshelf-1.12.2-2.3.590.jar"
hash-format = "murmur2"
hash = "2546524333"

[update]
[update.curseforge]
file-id = 2836960
project-id = 228525
release-channel = "beta"
