name = "Death Compass"
filename = "DeathCompass-0.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2555/77/DeathCompass-0.0.3.jar"
hash-format = "murmur2"
hash = "3491329278"

[update]
[update.curseforge]
file-id = 2555077
project-id = 290702
release-channel = "beta"
