name = "DimensionalDoors"
filename = "DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2946/179/DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL.jar"
hash-format = "murmur2"
hash = "2184682035"

[update]
[update.curseforge]
file-id = 2946179
project-id = 284876
release-channel = "beta"
