name = "Electroblob's Wizardry: Twilight Forest Spell Pack"
filename = "TFSpellPack-1.1.0-MC1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3140/441/TFSpellPack-1.1.0-MC1.12.2.jar"
hash-format = "murmur2"
hash = "2064129557"

[update]
[update.curseforge]
file-id = 3140441
project-id = 363993
release-channel = "beta"
