name = "EvilCraft"
filename = "EvilCraft-1.12.2-0.10.78.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2811/267/EvilCraft-1.12.2-0.10.78.jar"
hash-format = "murmur2"
hash = "3670568557"

[update]
[update.curseforge]
file-id = 2811267
project-id = 74610
release-channel = "beta"
