name = "Extra Alchemy"
filename = "extraalchemy-forge-1.12-build11-0.5.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2937/550/extraalchemy-forge-1.12-build11-0.5.4.jar"
hash-format = "murmur2"
hash = "851743633"

[update]
[update.curseforge]
file-id = 2937550
project-id = 247357
release-channel = "beta"
