name = "Fairy Lights"
filename = "fairylights-2.2.0-1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3068/499/fairylights-2.2.0-1.12.2.jar"
hash-format = "murmur2"
hash = "3333912711"

[update]
[update.curseforge]
file-id = 3068499
project-id = 233342
release-channel = "beta"
