name = "Fish's Undead Rising"
filename = "Fish's Undead Rising-1.2.4a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3283/582/Fish's Undead Rising-1.2.4a.jar"
hash-format = "murmur2"
hash = "1947217132"

[update]
[update.curseforge]
file-id = 3283582
project-id = 321139
release-channel = "beta"
