name = "Friendly Fire"
filename = "FriendlyFire-1.12.2-1.5.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2758/672/FriendlyFire-1.12.2-1.5.12.jar"
hash-format = "murmur2"
hash = "1560644648"

[update]
[update.curseforge]
file-id = 2758672
project-id = 255105
release-channel = "beta"
