name = "Global XP"
filename = "globalxp-1.12.2-v1.4.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2818/519/globalxp-1.12.2-v1.4.10.jar"
hash-format = "murmur2"
hash = "3387007153"

[update]
[update.curseforge]
file-id = 2818519
project-id = 268647
release-channel = "beta"
