name = "Guide-API"
filename = "Guide-API-1.12-2.1.8-63.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2645/992/Guide-API-1.12-2.1.8-63.jar"
hash-format = "murmur2"
hash = "1899009469"

[update]
[update.curseforge]
file-id = 2645992
project-id = 228832
release-channel = "beta"
