name = "Hardcore Darkness"
filename = "HardcoreDarkness-MC1.12.2-2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2499/443/HardcoreDarkness-MC1.12.2-2.0.jar"
hash-format = "murmur2"
hash = "1381892724"

[update]
[update.curseforge]
file-id = 2499443
project-id = 225957
release-channel = "beta"
