name = "LibraryEx"
filename = "LibraryEx-1.12.2-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3137/253/LibraryEx-1.12.2-1.2.1.jar"
hash-format = "murmur2"
hash = "3808448302"

[update]
[update.curseforge]
file-id = 3137253
project-id = 298965
release-channel = "beta"
