name = "Mo' Bends"
filename = "MoBends_1.12.2-1.0.0-beta-20.06.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2984/182/MoBends_1.12.2-1.0.0-beta-20.06.20.jar"
hash-format = "murmur2"
hash = "3005741541"

[update]
[update.curseforge]
file-id = 2984182
project-id = 231347
release-channel = "beta"
