name = "Mob Dismemberment"
filename = "MobDismemberment-1.12.2-7.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2487/81/MobDismemberment-1.12.2-7.0.0.jar"
hash-format = "murmur2"
hash = "1814999168"

[update]
[update.curseforge]
file-id = 2487081
project-id = 229067
release-channel = "beta"
