name = "NetherEx"
filename = "NetherEx-1.12.2-2.2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3177/625/NetherEx-1.12.2-2.2.4.jar"
hash-format = "murmur2"
hash = "1403438057"

[update]
[update.curseforge]
file-id = 3177625
project-id = 248039
release-channel = "beta"
