name = "Placebo"
filename = "Placebo-1.12.2-1.6.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2694/382/Placebo-1.12.2-1.6.0.jar"
hash-format = "murmur2"
hash = "2862833350"

[update]
[update.curseforge]
file-id = 2694382
project-id = 283644
release-channel = "beta"
