name = "Refined Storage"
filename = "refinedstorage-1.6.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2940/914/refinedstorage-1.6.16.jar"
hash-format = "murmur2"
hash = "3949468729"

[update]
[update.curseforge]
file-id = 2940914
project-id = 243076
release-channel = "beta"
