name = "Spartan Shields"
filename = "SpartanShields-1.12.2-1.5.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2712/229/SpartanShields-1.12.2-1.5.4.jar"
hash-format = "murmur2"
hash = "681427294"

[update]
[update.curseforge]
file-id = 2712229
project-id = 252239
release-channel = "beta"
