name = "Spartan Weaponry"
filename = "SpartanWeaponry-1.12.2-beta-1.3.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2830/166/SpartanWeaponry-1.12.2-beta-1.3.8.jar"
hash-format = "murmur2"
hash = "15740874"

[update]
[update.curseforge]
file-id = 2830166
project-id = 278141
release-channel = "beta"
