name = "The Erebus"
filename = "Erebus-1.0.32.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3211/974/Erebus-1.0.32.jar"
hash-format = "murmur2"
hash = "3366003449"

[update]
[update.curseforge]
file-id = 3211974
project-id = 220698
release-channel = "beta"
