name = "Vampirism - Become a vampire!"
filename = "Vampirism-1.12.2-1.6.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2890/62/Vampirism-1.12.2-1.6.2.jar"
hash-format = "murmur2"
hash = "1016293188"

[update]
[update.curseforge]
file-id = 2890062
project-id = 233029
release-channel = "beta"
