name = "Vampirism Integrations"
filename = "VampirismIntegrations-1.12.2-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2947/539/VampirismIntegrations-1.12.2-1.3.0.jar"
hash-format = "murmur2"
hash = "3496542301"

[update]
[update.curseforge]
file-id = 2947539
project-id = 282433
release-channel = "beta"
