name = "Wolf Armor and Storage (Legacy)"
filename = "wolfarmor-1.12.2-3.7.5-universal-signed.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3055/980/wolfarmor-1.12.2-3.7.5-universal-signed.jar"
hash-format = "murmur2"
hash = "3544791260"

[update]
[update.curseforge]
file-id = 3055980
project-id = 253689
release-channel = "beta"
