name = "Zombie Awareness"
filename = "zombieawareness-1.12.1-1.11.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2663/393/zombieawareness-1.12.1-1.11.16.jar"
hash-format = "murmur2"
hash = "4139434154"

[update]
[update.curseforge]
file-id = 2663393
project-id = 237754
release-channel = "beta"
